plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.74'
}

group = 'com.novoidstructures'
version = '1.0.0'

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = '21.1.172'

    parchment {
        minecraftVersion = '1.21.1'
        mappingsVersion = '2024.11.17'
    }

    mods {
        no_void_structures {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
